export const TOP_MNCS = [
  { name: "Google", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/512px-Google_2015_logo.svg.png", link: "https://careers.google.com/locations/india/" },
  { name: "Microsoft", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/512px-Microsoft_logo.svg.png", link: "https://careers.microsoft.com/v2/global/en/home" },
  { name: "Amazon", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/512px-Amazon_logo.svg.png", link: "https://www.amazon.jobs/en/locations/india" },
  { name: "IBM", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/IBM_logo.svg/512px-IBM_logo.svg.png", link: "https://www.ibm.com/in-en/careers" },
  { name: "TCS", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/512px-Tata_Consultancy_Services_Logo.svg.png", link: "https://www.tcs.com/careers" },
  { name: "Infosys", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Infosys_logo.svg/512px-Infosys_logo.svg.png", link: "https://www.infosys.com/careers.html" },
  { name: "Wipro", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Wipro_Primary_Logo_Color_RGB.svg/512px-Wipro_Primary_Logo_Color_RGB.svg.png", link: "https://careers.wipro.com/careers-home/" },
  { name: "Accenture", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Accenture.svg/512px-Accenture.svg.png", link: "https://www.accenture.com/in-en/careers" },
  { name: "Cognizant", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Cognizant_logo_2022.svg/512px-Cognizant_logo_2022.svg.png", link: "https://careers.cognizant.com/global/en" },
  { name: "Capgemini", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Capgemini_2017_logo.svg/512px-Capgemini_2017_logo.svg.png", link: "https://www.capgemini.com/in-en/careers/" },
  { name: "Apple", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/512px-Apple_logo_black.svg.png", link: "https://www.apple.com/jobs/in/" },
  { name: "Meta", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Meta_Platforms_Inc._logo.svg/512px-Meta_Platforms_Inc._logo.svg.png", link: "https://www.metacareers.com/locations/india/" },
  { name: "Netflix", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Netflix_2015_logo.svg/512px-Netflix_2015_logo.svg.png", link: "https://jobs.netflix.com/locations/india" },
  { name: "Adobe", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Adobe_Systems_logo_and_wordmark.svg/512px-Adobe_Systems_logo_and_wordmark.svg.png", link: "https://careers.adobe.com/us/en/india" },
  { name: "Salesforce", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Salesforce.com_logo.svg/512px-Salesforce.com_logo.svg.png", link: "https://www.salesforce.com/in/company/careers/" },
  { name: "Oracle", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Oracle_logo.svg/512px-Oracle_logo.svg.png", link: "https://careers.oracle.com/jobs/" },
  { name: "SAP", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/SAP_2011_logo.svg/512px-SAP_2011_logo.svg.png", link: "https://jobs.sap.com/location/india-jobs/" },
  { name: "Intel", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Intel_logo_2023.svg/512px-Intel_logo_2023.svg.png", link: "https://jobs.intel.com/en/locations/india" },
  { name: "Cisco", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Cisco_logo_blue_2016.svg/512px-Cisco_logo_blue_2016.svg.png", link: "https://jobs.cisco.com/jobs/SearchJobs/?country=India" },
  { name: "Dell", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Dell_logo_2016.svg/512px-Dell_logo_2016.svg.png", link: "https://jobs.dell.com/india" },
  { name: "HP", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/HP_logo_2012.svg/512px-HP_logo_2012.svg.png", link: "https://jobs.hp.com/en-us/search-jobs?k=&l=India" },
  { name: "Samsung", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Samsung_Logo.svg/512px-Samsung_Logo.svg.png", link: "https://research.samsung.com/sri-b" },
  { name: "Nvidia", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Nvidia_logo.svg/512px-Nvidia_logo.svg.png", link: "https://www.nvidia.com/en-in/about-nvidia/careers/" },
  { name: "Qualcomm", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Qualcomm-Logo.svg/512px-Qualcomm-Logo.svg.png", link: "https://careers.qualcomm.com/careers" },
  { name: "VMware", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Vmware.svg/512px-Vmware.svg.png", link: "https://careers.vmware.com/main/jobs?location=India" },
  { name: "Walmart Global Tech", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Walmart_logo.svg/512px-Walmart_logo.svg.png", link: "https://walmartglobaltech.com/careers" },
  { name: "Goldman Sachs", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Goldman_Sachs.svg/512px-Goldman_Sachs.svg.png", link: "https://www.goldmansachs.com/careers/" },
  { name: "JPMorgan Chase", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/JPMorgan_Chase_Logo.svg/512px-JPMorgan_Chase_Logo.svg.png", link: "https://careers.jpmorgan.com/global/en/locations/india" },
  { name: "Morgan Stanley", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Morgan_Stanley_Logo_1.svg/512px-Morgan_Stanley_Logo_1.svg.png", link: "https://www.morganstanley.com/about-us/global-offices/india" },
  { name: "American Express", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/American_Express_logo_%282018%29.svg/512px-American_Express_logo_%282018%29.svg.png", link: "https://aexp.eightfold.ai/careers?location=India" },
  { name: "Mastercard", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Mastercard-logo.svg/512px-Mastercard-logo.svg.png", link: "https://careers.mastercard.com/us/en" },
  { name: "Visa", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Visa_Inc._logo.svg/512px-Visa_Inc._logo.svg.png", link: "https://www.visa.co.in/careers.html" },
  { name: "PayPal", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/PayPal.svg/512px-PayPal.svg.png", link: "https://careers.paypal.com/us/en" },
  { name: "Intuit", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Intuit_logo.svg/512px-Intuit_logo.svg.png", link: "https://jobs.intuit.com/location/india-jobs/" },
  { name: "LinkedIn", logo: "https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png", link: "https://careers.linkedin.com/" },
  { name: "Uber", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Uber_logo_2018.svg/512px-Uber_logo_2018.svg.png", link: "https://www.uber.com/in/en/careers/" },
  { name: "Airbnb", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Airbnb_Logo_Bélo.svg/512px-Airbnb_Logo_Bélo.svg.png", link: "https://careers.airbnb.com/" },
  { name: "Siemens", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Siemens-logo.svg/512px-Siemens-logo.svg.png", link: "https://jobs.siemens.com/jobs?country=India" },
  { name: "Bosch", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Bosch_logo.svg/512px-Bosch_logo.svg.png", link: "https://www.bosch.in/careers/" },
  { name: "General Electric", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/General_Electric_logo.svg/512px-General_Electric_logo.svg.png", link: "https://jobs.gecareers.com/global/en/india" },
  { name: "Boeing", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Boeing_full_logo.svg/512px-Boeing_full_logo.svg.png", link: "https://jobs.boeing.com/location/india-jobs/" },
  { name: "Ford", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Ford_Motor_Company_Logo.svg/512px-Ford_Motor_Company_Logo.svg.png", link: "https://corporate.ford.com/careers.html" },
  { name: "Sony", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Sony_logo.svg/512px-Sony_logo.svg.png", link: "https://www.sony.co.in/microsite/careers/" },
  { name: "L&T", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/L%26T_logo.svg/512px-L%26T_logo.svg.png", link: "https://www.larsentoubro.com/corporate/careers/" },
  { name: "Tech Mahindra", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Tech_Mahindra_New_Logo.svg/512px-Tech_Mahindra_New_Logo.svg.png", link: "https://careers.techmahindra.com/" },
  { name: "HCLTech", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/HCLTech_logo.svg/512px-HCLTech_logo.svg.png", link: "https://www.hcltech.com/careers" },
  { name: "Mindtree", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/8/87/LTIMindtree_Logo.svg/512px-LTIMindtree_Logo.svg.png", link: "https://www.ltimindtree.com/careers/" },
  { name: "Deloitte", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Deloitte.svg/512px-Deloitte.svg.png", link: "https://www2.deloitte.com/in/en/careers/careers.html" },
  { name: "PwC", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/PricewaterhouseCoopers_Logo.svg/512px-PricewaterhouseCoopers_Logo.svg.png", link: "https://www.pwc.in/careers.html" },
  { name: "EY", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/EY_logo_2019.svg/512px-EY_logo_2019.svg.png", link: "https://www.ey.com/en_in/careers" },
];
